app_id: "b958914e-2e69-4cab-b7ac-8c7d63ad41ba"
app_secret: "03u.8dd.qB32~8p_~3CrcaamhgS12HI8OU"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read calendars.readwrite"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
